version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:10.8
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: 'pguser'
      POSTGRES_PASSWORD: 'pguserpass'
      POSTGRES_DB: 'auditlogger'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
      DB_CONNECTION_STRING: 'Server=postgres;Port=5432;Database=auditlogger;User Id=pguser;Password=pguserpass'
    depends_on:
      - postgres
    networks:
      - internal
      - web
volumes:
  pgdata:

networks:
  internal:
  web:
    external:
      name: nginx_web
